sonar.organization=hikaru-izumitani
sonar.projectKey=hikaru-izumitani_data6580

sonar.sources=./data5580_hw
sonar.tests=./tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=.github/**, data5580_hw/notebooks/**

## Hikaru Izumitani
sonar.branch.name=main
sonar.python.version=3.11

#sonar.coverage.exclusions=tests/**,data5580_hw/notebooks/**

#sonar.tests=tests
#sonar.test.inclusions=tests/**
#sonar.exclusions=data5580_hw/tests/**,data5580_hw/notebooks/**,data5580_hw/**/__pycache__/**,.github/**
#sonar.coverage.exclusions=tests/**,data5580_hw/notebooks/**
#sonar.cpd.exclusions=tests/**
#sonar.python.coverage.reportPaths=coverage.xml
#sonar.sourceEncoding=UTF-8