sonar.projectKey=hikaru-izumitani_data6580
sonar.organization=hikaru-izumitani

sonar.sources=data5580_hw
sonar.tests=data5580_hw/tests
sonar.exclusions=data5580_hw/tests/**,data5580_hw/notebooks/**,data5580_hw/**/__pycache__/**,.github/**
sonar.coverage.exclusions=data5580_hw/tests/**,data5580_hw/notebooks/**
sonar.cpd.exclusions=data5580_hw/tests/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8